name: print env vars
description: pritn env vars for testing
runs:
 using: composite
 steps:
   - name: print job level env vars
     run: echo "${{ env.ALLMYVARS }}"
     shell: bash
   - name: run shell script
     run: |
       chmod +x .github/scripts/test.sh
       ./.github/scripts/test.sh
     shell: bash  
       
