name: list vars
on:
  workflow_dispatch:
env:
 ORG_VARS: ${{ toJSON(vars) }}
jobs:
 test:
   env:
     ALLMYVARS: ${{ toJSON(vars) }}
   runs-on: ubuntu-latest
   steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: print env vars
      run: |
        echo "terraform_state_bucket=stb" >> $GITHUB_ENV
        echo "terraform_lock_table=tlt" >> $GITHUB_ENV

    - name: print job env vars
      uses: ./.github/actions
      
    # - name: list all vars
    #   run: env
    #   shell: bash
    #   env:
    #     ALLMYVARS: ${{ toJSON(vars) }}
